apiVersion: apps/v1
kind: Deployment
metadata:
  name: ristorante-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ristorante
  template:
    metadata:
      labels:
        app: ristorante
    spec:
      containers:
        - name: ristorante-container
          image: your-docker-image:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
