apiVersion: apps/v1
kind: Deployment
metadata:
  name: ristorante
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ristorante
  template:
    metadata:
      labels:
        app: ristorante
    spec:
      containers:
        - name: ristorante
          image: desiana04/ristorante:1.0.4
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: ristorante-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: ristorante
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ristorante-hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ristorante
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
